fix jq issues that would kill mod .jsons

diff --git a/mcmrecorder-cleaner b/mcmrecorder-cleaner
--- a/mcmrecorder-cleaner
+++ b/mcmrecorder-cleaner
@@ -38,11 +38,18 @@ do
         mod1="${modmap[$modname]}$modname"
         mod2="$uniqueindex$modname"
 
-        jq -s '.[0] + .[1]' "$mod1" "$mod2" > "./temp"
+        cp "$mod1" "./temp"
 
-        mv "./temp" "./$mod1"
+        jq -s '.[0] + .[1]' "$mod1" "$mod2" > "$mod1"
+
+        if [[ $? != 0 ]]
+        then
+            echo -e "\033[31;1;1mERROR: jq failed.\033[0;0m"
+            mv "./temp" "$mod1"
+            exit -1;
+        fi
+
         rm "./$mod2"
-
         echo -e "\033[33;1;3mmerged $mod2 into $mod1!\033[0;0m"
 
         mergecount="$(($mergecount + 1))"
@@ -53,7 +60,7 @@ done
 
 if [[ -f "./temp" ]]
 then
-    rm ./temp
+    rm "./temp"
 fi
 
 echo -e "\033[32;1;1mreduction: $jsoncount -> $uniquemods"
