confirm overwriting

diff --git a/nitrogen-profile b/nitrogen-profile
--- a/nitrogen-profile
+++ b/nitrogen-profile
@@ -12,9 +12,25 @@ then
     then
         echo -e "\n\033[31;1;1ma no name specified to save profile as.\033[0m\n"
         exit 1;
+    else
+    if [[ -f "profile-$2" ]]
+    then
+        echo "configuration exists."
+        read -p "Do you wish to overwrite profile-$2? (y/N): " -r
+        if [[ $REPLY =~ ^[Yy]$ ]]
+        then
+            cp bg-saved.cfg profile-$2
+            echo -e "overwritten profile-$2 with current configuration."
+        else
+            echo -e "aborted."
+            exit 2;
+        fi
     fi
+    fi
+
     cp bg-saved.cfg profile-$2
     echo -e "saved current configuration as profile-$2."
+
     popd > /dev/null
     exit 0;
 else
