restructure if/else, fortify control flow & errors

diff --git a/nitrogen-profile b/nitrogen-profile
--- a/nitrogen-profile
+++ b/nitrogen-profile
@@ -11,59 +11,6 @@ fi
 
 pushd $HOME/.config/nitrogen > /dev/null
 
-if [[ $1 = "random" ]]
-then
-    theme=$(ls -I bg-saved.cfg -I nitrogen.cfg | shuf -n 1)
-else
-if [[ $1 = "save" ]]
-then
-    if [[ $2 = "" ]]
-    then
-        echo -e "\n\033[31;1;1ma no name specified to save profile as.\033[0m\n"
-        exit 1;
-    else
-    if [[ -f "profile-$2" ]] || [[ -f "$SAVEDIR/profile-$2" ]]
-    then
-        echo "configuration exists."
-        read -p "Do you wish to overwrite profile-$2? (y/N): " -r
-        if [[ ! $REPLY =~ ^[Yy]$ ]]
-        then
-            echo -e "aborted."
-            exit 2;
-        fi
-    fi
-    fi
-
-    cp "bg-saved.cfg" "profile-$2"
-    cp "bg-saved.cfg" "$SAVEDIR/profile-$2"
-    echo -e "saved current configuration as profile-$2 in:"
-    echo -e "$HOME/.config/nitrogen/ \nand\n$SAVEDIR"
-
-    popd > /dev/null
-    exit 0;
-else
-if [[ $1 = "delete" ]]
-then
-    if [[ $2 = "" ]]
-    then
-        echo -e "\n\033[31;1;1ma no profile to delete specified.\033[0m\n"
-        exit 1;
-    else
-    if [[ ! -f "profile-$2" ]] && [[ ! -f "$SAVEDIR/profile-$2" ]]
-    then
-        echo -e "\033[31;1;1mERROR: a configuration of name '$2' does not exist, can't delete.\033[0m\n"
-        exit 1;
-    fi
-    fi
-
-    rm "profile-$2"
-    rm "$SAVEDIR/profile-$2"
-    echo -e "successfully deleted configuration profile-$2 from:"
-    echo -e "$HOME/.config/nitrogen/ \nand\n$SAVEDIR"
-
-    popd > /dev/null
-    exit 0;
-else
 if [[ $1 = "list" ]]
 then
     list=$(ls -I bg-saved.cfg -I nitrogen.cfg)
@@ -76,7 +23,7 @@ then
         if [[ $name =~ ^profile-${last_theme}-([0-9]+)$ ]]
         then
             continue;
-        else if [[ $name =~ ^profile-(.+)-([0-9]+)$ ]]
+        elif [[ $name =~ ^profile-(.+)-([0-9]+)$ ]]
         then
             theme="${BASH_REMATCH[1]}"
             last_theme=$theme
@@ -101,21 +48,63 @@ then
                 echo -n "[$max_index]"
             fi
             echo " $theme"
-        else if [[ $name =~ ^profile-(.+)$ ]]
+        elif [[ $name =~ ^profile-(.+)$ ]]
         then
             theme="${BASH_REMATCH[1]}"
             echo "     $theme"
         fi
-        fi
-        fi
     done
 
-    echo -e "\nTotal theme count: $count"
+    echo -e "\nTotal theme count: $count.\n"
 
-    popd > /dev/null
-    exit 0;
+elif [[ $1 = "save" ]]
+then
+    if [[ $2 = "" ]]
+    then
+        echo -e "\n\033[31;1;1mERROR: no name specified to save theme as.\033[0m\n"
+        exit 1;
+    elif [[ -f "profile-$2" ]] || [[ -f "$SAVEDIR/profile-$2" ]]
+    then
+        echo "configuration exists."
+        read -p "Do you wish to overwrite profile-$2? (y/N): " -r
+        if [[ ! $REPLY =~ ^[Yy]$ ]]
+        then
+            echo -e "aborted."
+            exit 2;
+        fi
+    fi
+
+    cp "bg-saved.cfg" "profile-$2"
+    cp "bg-saved.cfg" "$SAVEDIR/profile-$2"
+    echo -e "saved current configuration as 'profile-$2' in:"
+    echo -e "$HOME/.config/nitrogen/ \nand\n$SAVEDIR"
+
+elif [[ $1 = "delete" ]]
+then
+    if [[ $2 = "" ]]
+    then
+        echo -e "\n\033[31;1;1ma no profile to delete specified.\033[0m\n"
+        exit 1;
+    else
+    if [[ ! -f "profile-$2" ]] && [[ ! -f "$SAVEDIR/profile-$2" ]]
+    then
+        echo -e "\033[31;1;1mERROR: a configuration of name '$2' does not exist, can't delete.\033[0m\n"
+        exit 1;
+    fi
+    fi
+
+    rm "profile-$2"
+    rm "$SAVEDIR/profile-$2"
+    echo -e "successfully deleted configuration profile-$2 from:"
+    echo -e "$HOME/.config/nitrogen/ \nand\n$SAVEDIR"
+
 else
-    theme="profile-$1"
+    if [[ $1 = "random" ]]
+    then
+        theme=$(ls -I bg-saved.cfg -I nitrogen.cfg | shuf -n 1)
+    else
+        theme="profile-$1"
+    fi
 
     if [[ ! -f $theme ]] && [[ -f "$theme-0" ]]
     then
@@ -129,19 +118,15 @@ else
         final=$(seq $count | shuf -n 1)
         theme="$theme-$((final - 1))"
 
-    else
-        if [[ ! -f $theme ]]
-        then
-            echo -e "\033[31;1;1mERROR: a configuration of name '$1' does not exist.\033[0m\n"
-            popd > /dev/null
-            exit 1;
-        fi
+    elif [[ ! -f $theme ]]
+    then
+        echo -e "\033[31;1;1mERROR: a configuration of name '$1' does not exist.\033[0m\n"
+        popd > /dev/null
+        exit 1;
     fi
-fi
-fi
-fi
+
+    cp $theme bg-saved.cfg
 fi
 
-cp $theme bg-saved.cfg
 nitrogen --restore 2> /dev/null &
 popd > /dev/null
