delete configs

diff --git a/nitrogen-profile b/nitrogen-profile
--- a/nitrogen-profile
+++ b/nitrogen-profile
@@ -18,6 +18,25 @@ then
     popd > /dev/null
     exit 0;
 else
+if [[ $1 = "delete" ]]
+then
+    if [[ $2 = "" ]]
+    then
+        echo -e "\n\033[31;1;1ma no profile to delete specified.\033[0m\n"
+        exit 1;
+    else
+    if [[ ! -f "profile-$2" ]]
+    then
+        echo -e "\n\033[31;1;1ma profile-$2 does not exist, can't delete.\033[0m\n"
+        exit 1;
+    fi
+    fi
+
+    rm profile-$2
+    echo -e "successfully deleted configuration profile-$2."
+    popd > /dev/null
+    exit 0;
+else
 if [[ $1 = "list" ]]
 then
     for name in $(ls -I bg-saved.cfg -I nitrogen.cfg)
@@ -49,6 +68,7 @@ else
             exit 1;
         fi
     fi
+fi
 fi
 fi
 fi
